version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: "mongo-container"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: easy-generator
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-container"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/easy-generator
      JWT_SECRET: tifFvs/YNNjdWqaiqYg7gVNd+VeUBYeUHfTiBsy268M=

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-container"
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
